# Generated by Django 5.0.2 on 2024-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasm/images')),
                ('ismi', models.CharField(max_length=200)),
                ('kasbi', models.CharField(max_length=200)),
            ],
        ),
    ]
